### ISSUE TITLE
Repository's Readme should have pointer to installation instructions

### ISSUE THREAD

**Issue by Liamsi** [coniks-sys/coniks-go#139]
There should be a sub-section which simply points to the clients/servers installation instructions (in their Readmes).

**Comment by masomel** [comment]
Is this for 0.1.0?

**Comment by Liamsi** [comment]
> Is this for 0.1.0?

I left that open because I also wasn't sure. But yes, I think it makes sense even for 0.1.0.

**Comment by masomel** [comment]
Do you want to give this a try? Otherwise, I can.

**Comment by Liamsi** [comment]
I can do it in one hour (after dinner); if you don't want to wait feel free to give this a try.

**Comment by masomel** [comment]
No rush, I don't mind waiting. Thanks for taking care of this!
