### ISSUE TITLE
Use the VRF for computing the private index

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#14]

**Comment by Liamsi** [comment]
For computing the index we also need a (private-)key. Wasn't there already a discussion on where to put the VRF key, or am I mixing things up and the discussion was about sth. different?

In Section 3.4 of the paper it sound like one only needs the public key for generating the index: index for user u is generated by `i = H(VRF_K_VRF (u))` where "K_VRF is a public key belonging to the provider, and it is specified in the policy field of each STR" while in the appendix where the VRF is describe more explicitly it says: "`VRF_k(m) = H1(m)^k`" where k is a private key. 
Anyways, it sounds like the vrf key-pair should be a different one than the kp used for signing, right?
We need to store this keys somewhere and make the private-key accessible from the `computePrivateIndex` method (and the public key from the not-yet existing verifyPrivateIndex. 
If there are already some concrete plans I missed, it would be good to know before I introduce yet another field. Regarding to section 3.4 it looks like the natural choice for the public key would be the the str policy (?). 

I wasn't really able to follow the discussions the last 7-10 days ... So, if there was no discussion/decision I missed I'm sorry for the noise (and will come up with a simple proposal).

**Comment by c633** [comment]
> Wasn't there already a discussion on where to put the VRF key, or am I mixing things up and the discussion was about sth. different?

As far as I know, there wasn't any discussions on this issue yet. I think @masomel and @arlolra would agree with me that this issue is a place for all discussions about VRF. 

> Regarding to section 3.4 it looks like the natural choice for the public key would be the the str policy (?).

We already have a `Policies` interface with a `DefaultPolicies` struct. I think it makes sense to put the VRF key here, along with other policies (e.g., the epoch interval or `epochDeadline` as in the source code).

> Anyways, it sounds like the vrf key-pair should be a different one than the kp used for signing, right?

I think so.

**Comment by Liamsi** [comment]
OK, thanks alot for the quick reply!

>We already have a Policies interface with a DefaultPolicies struct. I think it makes sense to put the VRF key here, along with other policies (e.g., the epoch interval or epochDeadline as in the source code).

Makes sense. But the `Policies` interface would need methods `VrfPublic` and `VrfPrivate` then, right (or otherwise we would need to switch between the policy's type in `computePrivateIndex`)?

**Comment by Liamsi** [comment]
Started working on that in the branch [vrf_integration](https://github.com/coniks-sys/libmerkleprefixtree-go/tree/vrf_integration) (in case you want an early sneak-peek on the implications)

**Comment by c633** [comment]
> But the Policies interface would need methods VrfPublic and vrfPrivate then, right (or otherwise we would need to switch between the policy's type in computePrivateIndex)?

Yes. We didn't fix anything yet for the `Policies` interface.

**Comment by masomel** [comment]
Completely agree with everything @c633 has said so far. Thanks @Liamsi for getting started on this! I'll go take a look.

**Comment by masomel** [comment]
As an aside: can we close the [orig_coniks_vrf](https://github.com/coniks-sys/libmerkleprefixtree-go/tree/orig_coniks_vrf) branch?

**Comment by Liamsi** [comment]
> As an aside: can we close the orig_coniks_vrf branch?

Yes, I just deleted the orig_coniks_vrf branch.

**Comment by Liamsi** [comment]
@c633: These parts of the tests:
https://github.com/coniks-sys/libmerkleprefixtree-go/blob/master/merkletree_test.go#L83-L110
How did you come with them? Did you manually compute these positions in the tree (assuming the index was a hash)?
If I regenerate a (vrf) private key (randomly) it won't be possible to know the positions beforehand. 

@masomel @arlolra @c633: Do we want the tests to be deterministic (meaning the tests will always use the same private-key and produce always the same tree)? Than we could directly use a fixed/hardcoded index for the tests instead. Deterministic tests have the advantage that the tests are reproducible and the disadvantage that it tests a very specific scenario only.

**Comment by Liamsi** [comment]
Above comment might also be related to #16

**Comment by c633** [comment]
> Did you manually compute these positions in the tree (assuming the index was a hash)?

Yes,  I did. 
I'm thinking of checking out new branch, namely `test`, to resolve these test issues (including #16 and #18 ). What do you think?

**Comment by Liamsi** [comment]
Sound good to me!

**Comment by Liamsi** [comment]
But, I wouldn't completely ignore the test (or not merge sth to master which isn't tested/has failing tests). What I could do for this PR: remove the manually computed/not vrf-compatible  tree positions/levels parts of the test. The rest still looks useful to me.

**Comment by Liamsi** [comment]
Something like in 71e092db867e53e1cb4340f73857bc4cd58c0b53

**Comment by c633** [comment]
Yes. It seems fine to me. 
What do you think @masomel ?

**Comment by c633** [comment]
Just out of curiosity, does the server need a `verifyPrivateIndex`?

**Comment by masomel** [comment]
Yup, removing the portions of the tests that use manually computed indices seems fine to me.

> Do we want the tests to be deterministic (meaning the tests will always use the same private-key and produce always the same tree)? Than we could also consider to use a fixed/hardcoded index for the tests instead (would mean some refactoring, though). Deterministic tests have the advantage that the tests are reproducible and the disadvantage that it tests a very specific scenario only.

I think some tests should definitely be deterministic for the reproducibility. I'm trying to think of scenarios that we would want to test and could use non-deterministic tests for.

**Comment by masomel** [comment]
> Just out of curiosity, does the server need a ``verifyPrivateIndex``? 

It shouldn't. This is something the client should implement.

**Comment by c633** [comment]
> It shouldn't. This is something the client should implement.

At least, should the server publish something like `vrfProof` ?

**Comment by Liamsi** [comment]
>> It shouldn't. This is something the client should implement.

> At least, should the server publish something like vrfProof ?

I think yes. It should publish the vrf and it's proof. Otherwise the client couldn't have a chance to verify the proof, right?

**Comment by Liamsi** [comment]
And you can create both using coname's `vrf.Prove` instead of `vrf.Compute`.

**Comment by c633** [comment]
OK, thanks for clarifying!

**Comment by masomel** [comment]
>> At least, should the server publish something like ``vrfProof ``? 
> I think yes. It should publish the vrf and its proof. Otherwise the client couldn't have a chance to verify the proof, right?

Oh, I thought you meant the verification function. But yes, I agree that the VRF proof does need to be published. This should probably be included in the ``ProofNode``.
