### ISSUE TITLE
Document policies and other confs

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#141]
On https://github.com/coniks-sys/coniks-go/blob/master/keyserver/README.md

Running `coniksserver init` spits a config.toml with,

```
database = "coniks.db"
loaded_history_length = 1000000

[policies]
  epoch_deadline = 60
  vrf_key_path = "vrf.priv"
  sign_key_path = "sign.priv"

[[addresses]]
  address = "unix:///tmp/coniks.sock"
  allow_registration = true

...
```

but I don't know what units the `epoch_deadline` is?  Seconds?

Is the `database` useful yet?

We might need something similar for the client as well.

**Comment by arlolra** [comment]
Maybe even include some documentation in the config file itself?

**Comment by arlolra** [comment]
Is `LoadedHistoryLength` used?

**Comment by c633** [comment]
> Maybe even include some documentation in the config file itself?

I think so. 

> We might need something similar for the client as well.

Sorry, but what is the lacking part in the client?

**Comment by masomel** [comment]
> Sorry, but what is the lacking part in the client?

Right, the client config is already documented in its README. This was part of #132.

**Comment by arlolra** [comment]
RTFM, Arlo!
