### ISSUE TITLE
Version the executables?

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#147]
I imagine `coniksclient version` should do something?  Should probably be tied to the release. We have a protocol version in `protocol/version.go` but that's independent.

**Comment by masomel** [comment]
This would make sense to me. I was also thinking about this earlier. Might also be nice to print the version as part of `coniksclient -h`.

**Comment by c633** [comment]
Do you mean just the `coniksclient` or also `coniksbot` and `coniksserver`?

**Comment by masomel** [comment]
> Do you mean just the `coniksclient` or also `coniksbot` and `coniksserver`?

I think this should apply to all three executables.

Also, do we want to bump up the version with every release, or only bump it up if we make changes to a particular component, i.e. if we only make client changes, should only the client version change?

**Comment by arlolra** [comment]
Do you have a preference?  I'm inclined to just have one version to rule them all.

**Comment by c633** [comment]
> I'm inclined to just have one version to rule them all.

I think so. Then do you have any idea on what package we should put this constant in?

**Comment by arlolra** [comment]
the `version/` packages? :P

**Comment by arlolra** [comment]
That was with tongue in cheek.  Good question though.

**Comment by arlolra** [comment]
Resolved in #148
