### ISSUE TITLE
go install of CLIs results in `cli` binary, not respective binary name

### ISSUE THREAD

**Issue by masomel** [coniks-sys/coniks-go#194]
I've set `GOBIN=$GOPATH/bin`. If I run `go install github.com/coniks-sys/coniks-go/coniksserver/cli`, I end up with the `cli` binary, which will conflict with the other CLIs. If I run `go install github.com/coniks-sys/coniks-go/coniksserver/cli/coniksserver.go`, I get a "No such file or directory" error unless I run the command from `$GOPATH/src`, which isn't ideal.

We should either rename the `coniks*/cli` packages to reflect their binary names, or refactor the `coniks*` packages so we can use the `cli` sub-packages as top-level packages.

**Comment by c633** [comment]
Another inelegant solution is to go with `git clone ... && make`.

**Comment by masomel** [comment]
Right, I considered that, but like you said, that's an inelegant solution :)

**Comment by c633** [comment]
It looks great!

**Comment by c633** [comment]
It makes sense, but I think we could do further refactoring:
- Move `cli` packages to `/cli/{auditor,server,bot,client}`, we still can `go install github.com/coniks-sys/coniks-go/cli/{auditor, server, bot, client}` with expected name.
- Move `coniks*` packages (e.g., `/coniksserver/{server.go, listener.go}` to `impl/{auditor, server, bot, client}` so we can reuse that code to build the C library or whatever. (I borrowed the name `impl` from KT).

**Comment by masomel** [comment]
This sounds good to me. I think it makes sense to solve this issue before I finish #193, I can give this a shot since I've already started refactoring a bit.
