### ISSUE TITLE
Hash random bytes before putting them on the wire

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#23]
In several places we do `rand.Read(buf);` where eventually `buf` will be sent to the client.  I'm suggesting we additionally hash `buf = H(buf)` after the read.  Is this a thing we should do?

See https://trac.torproject.org/projects/tor/ticket/17694

/cc @Liamsi

**Comment by Liamsi** [comment]
I briefly consulted @Daeinar on his opinion here: He also agreed that it's a reasonable thing to do. I'll take care of that.

**Comment by Liamsi** [comment]
I searched for `rand` through the project on the master branch. Most occurrences where only in tests. The only relevant occurrence seems to be the tree nonce (at least it's the one I found so far). 
The `TB` seems fine (doesn't reveal bytes from `rand`) same with `prevEpoch`.
Will we make use of the salt field in `userLeafNode` btw? (currently it is only used in a test).

I wonder if missed some other occurrences.

**Comment by c633** [comment]
>  The only relevant occurrence seems to be the tree nonce (at least it's the one I found so far). 

How's about the `prevStrHash` in https://github.com/coniks-sys/coniks-go/blob/master/merkletree/pad.go#L51-L52?

> Will we make use of the salt field in userLeafNode btw? (currently it is only used in a test).

I think yes. This salt could be returned to the client to open the commitment. (cc @masomel)

**Comment by Liamsi** [comment]
> How's about the prevStrHash in https://github.com/coniks-sys/coniks-go/blob/master/merkletree/pad.go#L51-L52?

I thought it was already hashed here (but I was wrong) https://github.com/coniks-sys/coniks-go/blob/master/merkletree/pad.go#L57 Will remove the `else` case (and always do the hash after before calling `NewSTR`. Thanks!

> I think yes. This salt could be returned to the client to open the commitment. (cc @masomel)

Then it will also need be hashed (and hashed again for the commitment).

**Comment by c633** [comment]
> Then it will also need be hashed (and hashed again for the commitment).

Yes, agree.

**Comment by masomel** [comment]
> Then it will also need be hashed (and hashed again for the commitment).

Sounds good to me!
