### ISSUE TITLE
Separate crypto subpackage into its own repo?

### ISSUE THREAD

**Issue by masomel** [coniks-sys/coniks-go#26]
This will allow reuse by other libraries (e.g. CONIKS client library).

**Comment by arlolra** [comment]
Maybe we should consolidate all these repos as in https://github.com/agl/pond

```
coniks-go
 |- client
 |- crypto
 |- server
 |- utils
 |- bots
 |- merkletree
```

I would opt for this repo being the one consolidate on, since we're done the most work / discussion here.

**Comment by arlolra** [comment]
You could then rename `coniks-ref-implementation` to `coniks-java`

**Comment by masomel** [comment]
> Maybe we should consolidate all these repos as in https://github.com/agl/pond

Definitely also an option. As long as the subpackages can still be imported individually. It seems like agl's repo is mostly a single package.

> You could then rename ``coniks-ref-implementation`` to ``coniks-java``

I've been wanting to do that, so this would be a great time to do so.

**Comment by arlolra** [comment]
> As long as the subpackages can still be imported individually.

I believe they can.

**Comment by Liamsi** [comment]
> As long as the subpackages can still be imported individually.

They can.

**Comment by masomel** [comment]
> I would opt for this repo being the one consolidated on, since we've done the most work / discussion here.

I think this is a fine idea. Shall we go for it?

**Comment by arlolra** [comment]
Make it so.

**Comment by c633** [comment]
A yes from me.

**Comment by arlolra** [comment]
> A yes from me.

@c633 I apologize for having given the go-ahead without waiting to see how you felt :(

**Comment by c633** [comment]
> @c633 I apologize for having given the go-ahead without waiting to see how you felt :(

No, it's not a problem. Don't bother. Btw, should we close #27 too?

**Comment by c633** [comment]
For the #4 issues, should we also have a subpackage `storage` in the same level with other subpackages? e.g.:
```
coniks-go
 |- client
 |- crypto
 |- server
 |- utils
 |- bots
 |- merkletree
 |- storage
```

**Comment by arlolra** [comment]
> should we also have a subpackage storage in the same level with other subpackages? 

Seems reasonable to me.

**Comment by arlolra** [comment]
Done in ae15fa391144906fe241c77a88acb49defb3ba57
