### ISSUE TITLE
Add doc.go file to each subpackage

### ISSUE THREAD

**Issue by masomel** [coniks-sys/coniks-go#32]
- [x] bots
- [x] client
- [x] crypto
- [x] keyserver
- [x] merkletree
- [x] utils
- [x] protocol

**Comment by Liamsi** [comment]
Not sure if this is the right place but as it about documentation: An alternative to adding READMEs in each package could be adding a doc.go file (see here for an example of such a file: https://golang.org/src/encoding/gob/doc.go  and how the generated documentation would look like: https://godoc.org/encoding/gob)

**Comment by c633** [comment]
I'm working on this in #102. Cooperate with me if you have time or have interest in this.
