### ISSUE TITLE
Reduce the size of cgo client library

### ISSUE THREAD

**Issue by c633** [coniks-sys/coniks-go#42]
The size of the library compiled with cgo is little large. We should have some ways to reduce its size.

**Comment by Liamsi** [comment]
Maybe this is helpful: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

**Comment by c633** [comment]
The same answer here: http://stackoverflow.com/a/37468877/1419789

**Comment by Liamsi** [comment]
Cool, saw that you already updated the makefile accordingly: https://github.com/coniks-sys/coniks-go/commit/624d18f
On my mac your changes shrink the `libconiks.dylib` file from  3.3M to 2.1M (which is a very reasonable size).
In @FiloSottile's blogpost there is another trick (using upx) but I guess this is only for executables. We could keep that in mind if we ever wanted to shrink the size of the server etc.

**Comment by arlolra** [comment]
Is upx deterministic?

**Comment by Liamsi** [comment]
> Is upx deterministic?

Not sure. I didn't find anything (yet) but I suspect not. Are you doing deterministic builds?

**Comment by arlolra** [comment]
> Are you doing deterministic builds?

Yup https://trac.torproject.org/projects/tor/ticket/10942

**Comment by c633** [comment]
> Is upx deterministic?

As I know it is deterministic. But I'm not sure it's stable (with my experience) and I'm also not sure if upx supports .so or .dylib file (according to its homepage http://upx.sourceforge.net/)

**Comment by Liamsi** [comment]
To my knowledge it is meant for executables. I only brought it up in case we wanted to shrink other executables. Is this still open because the lib is still to large (even with the ld-flags in the Makefile) or just because we forgot to close it?

**Comment by c633** [comment]
It sounds like do not really have much options for us. I'm not sure whether we should close this issue, though.

**Comment by c633** [comment]
With go 1.7, the size of the compiled library is only `1329976` (~1.3MB) now. I think we can close this issue for now.
