### ISSUE TITLE
Use unsigned integers when dealing with non-negative values

### ISSUE THREAD

**Issue by Liamsi** [coniks-sys/coniks-go#53]
Discussion started here https://github.com/coniks-sys/coniks-go/pull/43#discussion_r73206002 (refactor `node.level` to an unsigned integer value *or* panic/err if methods that expect a non-negative int receive a negative on; find out which approach is safer/faster/more reasonable).

Also, clarify if and how we want to deal with overflows (also in case of uint(32/64) if we go with unsigned values).

**Comment by Liamsi** [comment]
An interesting read on the signed/unsigned question: http://www.soundsoftware.ac.uk/c-pitfall-unsigned

**Comment by masomel** [comment]
Good read! I did some small tests, and it seems like ``uint32``and ``uint64`` have the same underflow issue as described in the article. Given this, I think it might be safer to panic/err if methods that expect a non-negative int receive a negative one.
