### ISSUE TITLE
Server isn't opening the commitment

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#57]
We need to make this change,

```
type ProofNode interface {
	Level() int
	Index() []byte
	Value() []byte
	IsEmpty() bool
-	Commitment() []byte
+	Salt() []byte
}
```

then the client computes the digest with `Salt()`, `Value()`, and the `name` it looked up.

I think ... need to go back to the paper.

**Comment by masomel** [comment]
@arlolra You're right. It's the salt that needs to be returned.

**Comment by arlolra** [comment]
@masomel Great, thanks! Getting late in the day here.

**Comment by c633** [comment]
I think we still need to return `Commitment` as a part of `ProofNode`, for verification in case of proof of absence when 2 indices share the same prefix.

In f5bd0dcfca2e6094c40d5ab94aad909e8eeddaba, I suggest changing the way we compute the commitment: `commitment = commit(index || value)` instead of `commitment = commit(key || value)`. 

What do you think?

**Comment by arlolra** [comment]
> I think we still need to return Commitment as a part of ProofNode, for verification in case of proof of absence when 2 indices share the same prefix.

Hmm, I'd need to check it in the morning, but that probably means we need to send both the commitment and the salt.

> I suggest changing the way we compute the commitment: commitment = commit(index || value) instead of commitment = commit(key || value).

No, go read the paper where it talks about why we do the commitment.  It specifically mentions why we commit to the name, and not the index.

**Comment by arlolra** [comment]
> that probably means we need to send both the commitment and the salt

So, there's an extra step on top of what we have for the inclusion, where you `VerifyCommitment()`.

**Comment by c633** [comment]
> No, go read the paper where it talks about why we do the commitment. It specifically mentions why we commit to the name, and not the index.

But we're using VRF instead of VUF now, and AFAIK, our VRF should be collision resistance (as @Liamsi stated here https://github.com/coniks-sys/coniks-go/issues/7#issuecomment-229700505). Does VRF solve the problem?

**Comment by arlolra** [comment]
> But we're using VRF instead of VUF now, and AFAIK, our VRF should be collision resistance (as @Liamsi stated here #7 (comment)). Does VRF solve the problem?

The difference between a VUF and a VRF (as far as I can tell) is only in that the output of the VUF is not indistinguishable from random.  What @Liamsi is saying is that the particular construction we're using happens to be collision resistant, but I'm not sure if that is an inherent property of VRFs (and I'm guessing it isn't if the paper is particularly concerned about it).  So no, I think we should stick to committing to the name.  Also, we're sort of making the crypto pluggable, so there's no guaranteeing the next choice will be collision resistant as well.

**Comment by c633** [comment]
Thanks for this explanation! It's great!

**Comment by masomel** [comment]
a169421 LGTM.
