### ISSUE TITLE
Align GenerateKey signatures in vrf/sign

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#65]
See https://github.com/coniks-sys/coniks-go/pull/63#issuecomment-239392423

**Comment by Liamsi** [comment]
> Not sure I agree. If, for whatever reason, the public key cannot be generated from the private key at call time, (private.Public()), we can always augment the PrivateKey structure to store it at construction. 


(from: https://github.com/coniks-sys/coniks-go/pull/63#issuecomment-239469454)
Hmm, true. OK, I'm convinced: Let's drop the public key from key generation. 

>I suggest we should refactor the vrf package to export the same API's signature & key type as sign package. What do you think?

Do we want to completely align them. Meaning both return an aliased `ed25119.PrivateKey` as sign.go's does or only make both return a slice of byte?

**Comment by arlolra** [comment]
> Meaning both return an aliased ed25119.PrivateKey as sign.go's does or only make both return a slice of byte?

I think he meant more the signatures.

**Comment by c633** [comment]
> Do we want to completely align them. Meaning both return an aliased ed25119.PrivateKey as sign.go's does or only make both return a slice of byte?

I think we could still keep the current implementation of vrf (i.e., using the SHA3/SHAKE), just make the `PrivateKey` and `PublicKey` a slice of byte. 

> Then why not call it Serialize() like in other place we want a slice of byte from an object (used for serialization)? 

How's about if `key.Public()` return a `PublicKey` instance and then we have `func (pk *PublicKey) Serialize() []byte`?

**Comment by Liamsi** [comment]
> How's about if key.Public() return a PublicKey instance and then we have func (pk *PublicKey) Serialize() []byte?

Sounds good to me!

**Comment by Liamsi** [comment]
I can work on that (if Huy didn't already and if everyone agrees). Should be very quick to resolve.

**Comment by c633** [comment]
> if Huy didn't already and if everyone agrees

Yup, thanks!
