### ISSUE TITLE
Client cli

### ISSUE THREAD

**Issue by Liamsi** [coniks-sys/coniks-go#90]
The (test-)client command line interface should have the the following functionality:
- register a name-to-key binding
- update a name-to-key-binding
- lookup a key 

And deal with all the details/edge-cases that come with that, e.g, dealing with temporary bindings etc

The cli should clarify what a real client would need to implement _and_ what a client would need to know in advance/before doing its first request (like initial public key of the key-server, key-server's epoch duration, or "initial" STR if necessary).

For a start, we omit the possibility to alter the key-change policy (which is currently possible in the java-test client: https://github.com/coniks-sys/coniks-java/blob/master/coniks_test_client/src/main/java/org/coniks/coniks_test_client/TestClient.java#L447)

**Comment by c633** [comment]
@Liamsi Maybe we can reuse this testutil (https://github.com/coniks-sys/coniks-go/blob/master/keyserver/testutil/testutil.go#L124)?

**Comment by Liamsi** [comment]
Looks useful indeed. Thanks!

**Comment by Liamsi** [comment]
Is there an equivalent dealing with the registration (from a clients perspective/directly contacting the twitter bot)? I see there is also https://github.com/coniks-sys/coniks-go/blob/master/keyserver/testutil/testutil.go#L154 but this is only for internal communication, thouugh.

**Comment by c633** [comment]
> Is there an equivalent dealing with the registration (from a clients perspective/directly contacting the twitter bot)?

Yes, it is.

**Comment by Liamsi** [comment]
> Yes, it is.

Could you point me to the code? I didn't find code which actually send the particular DMs to the bot (only code that directly calls `TwitterBot.HandleRegistration`).
If the command line client should help implementing a real client it should also use the twitter API (like the TorMessenger would), I guess? 
Hope I can finish the client today/tomorrow...

**Comment by c633** [comment]
Oops, I misinterpreted your question. Sorry :(
I think we don't need to run a Twitter Bot in the command line client test, it should just connect to the server directly via a unix socket connection.
> If the command line client should help implementing a real client it should also use the twitter API (like the TorMessenger would)

Yes, if we decide to go to with a real client, we will need to use the twitter API (I think we can re-use the `go-twitter` package).

Ahh, sorry again :(

**Comment by Liamsi** [comment]
Thanks for your reply and no worries!

> I think we don't need to run a Twitter Bot in the command line client test, it could bypass the bot and just connect to the server directly via a unix socket connection.

OK, then I start with that. Although I think, for this client to be actually useful we would need it to got through the twitter bot, otherwise the registration is simplified so much that someone looking at the go-test-client won't figure out the how-to implement a "real" client.

**Comment by c633** [comment]
Should we close this?

**Comment by arlolra** [comment]
Yup

**Comment by c633** [comment]
TODO:

- [ ] Monitoring (see the bug in #138)

**Comment by Liamsi** [comment]
> TODO:
> [ ] Monitoring (see the bug in #138)

I opened #144 for this specific issue.
