### ISSUE TITLE
Make the usage of the registration bot optional/configurable

### ISSUE THREAD

**Issue by Liamsi** [coniks-sys/coniks-go#91]
Currently the server can not take registration requests from outside (only through the bot). We might want to make this behavior optional/configurable such that the server can be run without the registration bot in between:
https://github.com/coniks-sys/coniks-go/blob/1a0e2571ba28cb99f489fdf9ecc7b28e8cc4ff6e/keyserver/server.go#L158-L170

(Discussion started here: https://github.com/coniks-sys/coniks-go/pull/86#discussion_r80303660)

**Comment by masomel** [comment]
I should add that a case in which a server might not want/need to use the bot is when the server is also the identity provider (i.e. if Twitter ran its own key server for its users). The bot is primarily for key servers that are not first-party key servers, i.e. don't hand out identities in their own namespace, such as Tor Messenger.
