### ISSUE TITLE
Server "deadlock"

### ISSUE THREAD

**Issue by Liamsi** [coniks-sys/coniks-go#94]
By sending multiple lookup requests to the server it will block forever. Most probably this is because on lookup the `RLocks` are never released: 
https://github.com/coniks-sys/coniks-go/blob/f21ba86a4a3ca89a0e82e881adc22ecddc78ffd9/keyserver/listener.go#L103-L110
(last line should be `server.RUnlock()` instead)

**Comment by c633** [comment]
Thanks! I submitted #95 to fix this bug.

**Comment by Liamsi** [comment]
> Thanks! I submitted #95 to fix this bug.

Wow, that was quick :-) I also already changed it on my branch (I was wondering why my client made the server stop...) but thanks I'll merge that asap.
